name: Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: use-local
        uses: ./
